### ISSUE TITLE
Elaborate pipiline creation examples

### ISSUE THREAD

**Issue by zainmehdi** [srrg-sapienza/srrg2_slam_interfaces#1]
First of all I would like to thank and congratulate you for coming up with such a wonderful framework. It would be really nice if you could also include examples of creating an interface out of your framework. You have provided lidar slam and vslam examples but they are a bit hard to understand at this stage. I know its still early stage but a step by step short tutorial explaining interface creation and sample slam app would be really helpful.

Thanks

**Comment by rvp-group** [comment]
We are working on a Tutorial in the Wiki section. Coming soon
